// 老师课件/demo3/typeScript/vue-ts/src/views/home/index.vue
<template>
    <div class="list">
        <div v-for="(item,index) in list" :key="index">
            <hero-item :hero="item"></hero-item>
        </div>
    </div>
  </template>
  <script lang="ts">
  import request from '@/utils/request'
  import heroItem from '@/components/heroItem.vue'
  import Vue from 'vue';
  export default Vue.extend({
    data(){
      return{
        list:[]
      }
    },
    components:{
        heroItem
    },
    methods:{
  
    },
    async created(){
        let res = await request("/images/lol/act/img/js/heroList/hero_list.js","GET");
        console.log(res)
        this.list = res.data.hero;
    }
  })
  </script>
  <style scoped>
  .list{
    width: 100%;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin-top: 10px;
  }
  </style>

// 老师课件/demo3/react/20221121/react-router/09-路由组件缓存/views/Home.jsx
import {useEffect,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import axios from 'axios';
import { useActivate } from 'react-activation';
export default function Home() {
  let [list,setList] = useState([]);
  useEffect(()=>{
    axios.get(`https://game.gtimg.cn/images/lol/act/img/js/heroList/hero_list.js`).then(res=>{
        console.log(res)
        setList(res.data.hero)
    })
  },[])
  let navgate = useNavigate();

  useActivate(()=>{
    console.log("组件再次激活后调用")
  })
  return (
    <div>
        {
            list.map((item,index) =>{
                return(
                    <div key={index} onClick={()=>{
                        navgate("/info")
                    }}>
                        <img src={`https://game.gtimg.cn/images/lol/act/img/champion/${item.alias}.png`} alt="" />
                        <div>{item.title}</div>
                    </div>
                )
            })
        }
    </div>
  )
}
