// work_Demo/teacher_3_vue,react,uniapp_20220810/20221114_react/day106_6_1121_react脚手架,配置路由,跳转页面/react-router/09_路由守卫，路由懒加载，监听路由_src/views/Login.js
import { useState } from "react";
import { useNavigate } from "react-router-dom";

function Login() {
    let [name, setName] = useState("");
    let [age, setAge] = useState("")
    let navigate = useNavigate();
    return (
        <div>
            姓名： <input type="text" onChange={(e) => {
                setName(e.target.value)
            }} /><br />
            年龄：<input type="text" onChange={(e) => {
                setAge(e.target.value)
            }} /> <br />
            <button className="button" onClick={() => {
                localStorage.setItem("token", { name, age });
                alert("登录成功")
                navigate("/home")
            }}>登录</button>
        </div>

    )
}

export default Login;

// 老师课件/demo3/vue/20220916/02_vue-router/src/views/login.vue
<template>
    <div>
        <input type="text" placeholder="请输入用户名" v-model="username">
        <br>
        <input type="text" placeholder="请输入密码" v-model="password">
        <br>
        <button @click="login">登录</button>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                username:"",
                password:""
            }
        },
        methods:{
            login(){
                localStorage.setItem("token",this.username)
                this.$router.go(-1)
            }
        }
    }
</script>
