// work_Demo/teacher_3_vue,react,uniapp_20220810/20220902__vue/day67__0916__10_vue-cli基本用法及路由，axios/02_vue-router/src/views/login.vue
<template>
    <div class="login">
       <input type="text" placeholder="请输入用户名" v-model="uname"><br>
       <input type="password" placeholder="请输入密码" v-model="pwd"><br>
       <button @click="login">登录</button>
    </div>
</template>
<script>

export default {
    data() {
        return {
            uname: '',
            pwd: "",
            state:"未登录",
        }
    },
    methods: {
        login() {
            if (localStorage.getItem("name")) {
                alert("你已经登录过");
            } else {
                localStorage.setItem("name", this.uname);
                this.$router.go(-1);
            }
            
        }
    }

}
</script>
<style>
    .login{
        margin:20px 0;
    }
    .login input{
        margin:5px 0;
    }
</style>

// work_Demo/teacher_3_vue,react,uniapp_20220810/20221114_react/day106_6_1121_react脚手架,配置路由,跳转页面/react-router/09_路由守卫，路由懒加载，监听路由_src/views/Login.js
import { useState } from "react";
import { useNavigate } from "react-router-dom";

function Login() {
    let [name, setName] = useState("");
    let [age, setAge] = useState("")
    let navigate = useNavigate();
    return (
        <div>
            姓名： <input type="text" onChange={(e) => {
                setName(e.target.value)
            }} /><br />
            年龄：<input type="text" onChange={(e) => {
                setAge(e.target.value)
            }} /> <br />
            <button className="button" onClick={() => {
                localStorage.setItem("token", { name, age });
                alert("登录成功")
                navigate("/home")
            }}>登录</button>
        </div>

    )
}

export default Login;
