// 老师课件/demo3/react/20221121/react-router/09-路由组件缓存/views/Home.jsx
import {useEffect,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import axios from 'axios';
import { useActivate } from 'react-activation';
export default function Home() {
  let [list,setList] = useState([]);
  useEffect(()=>{
    axios.get(`https://game.gtimg.cn/images/lol/act/img/js/heroList/hero_list.js`).then(res=>{
        console.log(res)
        setList(res.data.hero)
    })
  },[])
  let navgate = useNavigate();

  useActivate(()=>{
    console.log("组件再次激活后调用")
  })
  return (
    <div>
        {
            list.map((item,index) =>{
                return(
                    <div key={index} onClick={()=>{
                        navgate("/info")
                    }}>
                        <img src={`https://game.gtimg.cn/images/lol/act/img/champion/${item.alias}.png`} alt="" />
                        <div>{item.title}</div>
                    </div>
                )
            })
        }
    </div>
  )
}

// work_Demo/teacher_3_vue,react,uniapp_20220810/20221009_h5+,ts/081_1011/vue-ts/src/views/home/index.vue
<template>
  <div class="list">
    <div v-for="(item, index) in list" :key="index">
      <home-item :hero="item" class="heroitem"></home-item>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from "vue";
import homeItem from "@/components/homeItem.vue";
import request from "@/utils/request";
export default Vue.extend({
  data() {
    return {
      list: [],
    };
  },
  components: {
    homeItem,
  },
  async created() {
    let res = await request("https://game.gtimg.cn/images/lol/act/img/js/heroList/hero_list.js", "GET");
    console.log(res)
    this.list = res.data.hero;
  },
});
</script>

<style lang="less" scoped>
.list {
  width: 1200px;
  display: flex;
  justify-content: space-between;
  margin: 20px auto;
  flex-wrap: wrap;

  .heroitem {
    margin: 0 5px;
  }
}
</style>
